# Generated by Django 6.0.1 on 2026-04-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='back_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
