# Generated by Django 6.0.1 on 2026-04-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_back_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Used for fake discount. E.g. ~1999~ 1499', max_digits=10, null=True),
        ),
    ]
